name: Main

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install NuGet client
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Add private GitHub registry to NuGet
      run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/fedoranimus/index.json -Username fedoranimus -Password ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout Repo
      uses: actions/checkout@v1
      
    - name: Setup .NET Core
      run: dotnet test ./StatHat.Tests/StatHat.Tests.csproj
      
    - name: Package Library
      run: dotnet pack ./StatHat/StatHat.csproj --configuration Release --output nupkg

    - name: Push generated package to GitHub registry
      run: nuget push ./nupkg/StatHat.*.nupkg -Source "GPR" -SkipDuplicate
